version: "3"
services:
  launch-backend:
    build: ./
    restart: always
    ports:
      - "2500:2500" 
    depends_on:
      - db
    volumes:
      - /app/launch-backend

  db:
    image: mysql:latest
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: launch
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/mysql